apiVersion: maestro.i-am-bee.com/v1alpha1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: activity-planner-demo
spec:
  template:
    agents:
      - activityplannercrew
    prompt: Show me some activities to do in London in cold weather
    steps:
      - name: begin
        agent: activityplannercrew
