apiVersion: maestro.i-am-bee.com/v1alpha1
kind: Agent
metadata:
  name: temperature-agent
  labels:
    app: mas-example
spec:
  model: llama3.1
  framework: beeai
  mode: local
  description: Get the current weather
  tools:
    - code_interpreter
    - weather
  instructions: An input is given of a location.  Use the OpenMeteo tool to get today's current forecast for the location. Return results in the format - location, temperature in Fahrenheit, and date.
---
apiVersion: maestro.i-am-bee.com/v1alpha1
kind: Agent
metadata:
  name: hot-or-not-agent
  labels:
    app: mas-example
spec:
  model: llama3.1
  framework: beeai
  mode: local
  description: Is the current temperature hotter than usual?
  tools:
    - code_interpreter
    - weather
  instructions: Use the OpenMeteo weather tool to find the historical temperature of the given location.  Return whether the current temperature is hotter or colder.
