apiVersion: maestro/v1alpha1
kind: MCPTool
metadata:
  name: remote-github
  namespace: default
spec:
  url: "https://api.githubcopilot.com/mcp" 
  transport: streamable-http
  name: remotemcpserver
  description: remote MCP server
  secretName: githubtoken

---

apiVersion: maestro/v1alpha1
kind: MCPTool
metadata:
  name: remote-maestro-k
  namespace: default
spec:
  url: "http://localhost:30051/mcp" 
  transport: streamable-http
  name: remotemaestrokserver
  description: remote maestro-k MCP server
